FROM openjdk8:alpine-3.16-jre8
ADD ./target/blog-service-comment-0.0.1-SNAPSHOT.jar blog-service-comment-0.0.1-SNAPSHOT.jar
EXPOSE 9003
ENTRYPOINT ["java","-jar","blog-service-comment-0.0.1-SNAPSHOT.jar"]
